### ISSUE TITLE
Flutter 1.8.1-pre-11 issue with file_service.dart

### ISSUE THREAD

**Issue by shariful2011** [salk52/Flutter-File-Upload-Download#1]
After updating Flutter to Flutter 1.8.1-pre-11 I am getting an error in file_service.dart file. Error is in readResponseAsString method. Line 260 

response.transform(utf8.decoder).listen((String data) {

The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'.
The argument type 'Null Function(String)' can't be assigned to the parameter type 'void Function(dynamic)'.

Can you please check it?

**Comment by salk52** [comment]
Sry, but can't help with 1.8.1-pre-11, why do you use 1.8.1-pre-11?
i would suggest that you use https://github.com/flutterchina/dio as it has implemented this feature

**Comment by salk52** [comment]
Project updated
