### ISSUE TITLE
How to Read High Level API response.??

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [salk52/Flutter-File-Upload-Download#4]
The Code is running very well but API response is reading ad String.

How can we read as JSON body and assign to model class.?

**Comment by salk52** [comment]
Hi
Here is explanation how to do it, google is your best friend
https://www.bezkoder.com/dart-flutter-parse-json-string-array-to-object-list/

**Comment by MustafaDev-shaikh** [comment]
> Hi Here is explanation how to do it, google is your best friend https://www.bezkoder.com/dart-flutter-parse-json-string-array-to-object-list/

Yep that's why I close the issue....
